### ISSUE TITLE
Lock seed

### ISSUE THREAD

**Issue by dsgepers** [kwhitaker/toa-travel#3]
**Current Situation:**
- Seed is set when visiting the app
- Because of that the refresh button does nothing when pressed (without changing seed number)

**Improvement:**
I feel like it would be better to regenerate with a new seed every time the refresh button is pressed until they "lock" their seed number (maybe with a checkbox, or something)

Additional Note. maybe provide a direct URL too their current seed number.

**Comment by kwhitaker** [comment]
That makes a lot of sense.

**Comment by kwhitaker** [comment]
I've pushed a fix for the button, so it will refresh as expected now.
