### ISSUE TITLE
Suggestion: Add Beasts of Jungle Rot Options

### ISSUE THREAD

**Issue by PanoramicPanda** [kwhitaker/toa-travel#4]
[Beasts of Jungle Rot](http://www.dmsguild.com/product/220567/Beasts-of-the-Jungle-Rot) is an official supplement published on DM's Guild. While it's implementation is mostly manual substitution of CR equivalent monsters, there is a rule to allow the replacement of "Undead, Zombies" encounter with a roll on the Jungle Rot Expanded Zombies table (on page 24 of Beasts of Jungle Rot PDF). 

A simple "Beasts of Jungle Rot" checkbox enabling this table to be rolled on within the randomizer would be nice to see.

**Comment by kwhitaker** [comment]
I haven't purchased that supplement, but if I do I'll be sure to add them to the generator!

**Comment by PanoramicPanda** [comment]
I highly recommend it. It features a T-Rex that spews other undead, what's not to love? :)
